### ISSUE TITLE
vue-cli4 的vue-config.js 配置后报错  _htmlWebpackPlugin.default.getHooks is not a functio

### ISSUE THREAD

**Issue by carey4756** [GitOfZGT/theme-css-extract-webpack-plugin#1]
configureWebpack: {
    plugins: [
      new ThemeCssExtractWebpackPlugin({
        multipleScopeVars,
        defaultScopeName: 'theme-default',
        extract: process.env.NODE_ENV === 'production'
      })
    ]
  }

**Comment by GitOfZGT** [comment]
尝试通过 chainWebpack 追加在html-webpack-plugin 插件之后

**Comment by GitOfZGT** [comment]
> configureWebpack: {
> plugins: [
> new ThemeCssExtractWebpackPlugin({
> multipleScopeVars,
> defaultScopeName: 'theme-default',
> extract: process.env.NODE_ENV === 'production'
> })
> ]
> }

**Comment by GitOfZGT** [comment]
我经过测试，确实报错，是因为vue-cli 使用的 html-webpack-plugin 版本v3，这里需要html-webpack-plugin v4 + ；
既然如此，等我试着兼容 v3 发布一个新的版本。

**Comment by GitOfZGT** [comment]
v1.0.3 已支持  html-webpack-plugin v3
