### ISSUE TITLE
分离css后默认使用了第一个css，再去切换主题的时候会再加载一个css，可以默认不加载吗，节约css资源

### ISSUE THREAD

**Issue by yasuomang** [GitOfZGT/theme-css-extract-webpack-plugin#2]

**Comment by yasuomang** [comment]
document.documentElement.className = "theme-mauve";并且需要设置html的className，是我的使用姿势不对吗

**Comment by GitOfZGT** [comment]
那个加进去的link是有一个id的，切换直接换css，不用再添加一个link加载
```js
const toggleTheme = (scopeName = 'theme-default') => {
  let styleLink = document.getElementById('theme-link-tag');
  if (styleLink) {
    // 假如存在id为theme-link-tag 的link标签，直接修改其href
    styleLink.href = `/${scopeName}.css`;
 
  } 
   document.documentElement.className = scopeName;
};
```

**Comment by GitOfZGT** [comment]
那个加进去的link是有一个id的，切换直接换css，不用再添加一个link加载
```js
const toggleTheme = (scopeName = 'theme-default') => {
  let styleLink = document.getElementById('theme-link-tag');
  if (styleLink) {
    // 假如存在id为theme-link-tag 的link标签，直接修改其href
    styleLink.href = `/${scopeName}.css`;
 
  } 
   document.documentElement.className = scopeName;
};
```

**Comment by yasuomang** [comment]
![image](https://user-images.githubusercontent.com/62331159/140001066-2b47429e-cc21-43e9-b289-da98565d4703.png)
我没描述清楚我的问题，打包后的html文件会默认link一个theme-default.css，我这边的场景是页面加载前接口返回需要切换的主题，有且只有一次，我的想法是能否把默认link的theme-default.css去掉，因为此时我是不需要default主题的，否则会出现先加载了default再加载我想要的主题，加载了两次css资源。
![image](https://user-images.githubusercontent.com/62331159/140001406-26af5a6b-78ec-424d-b9eb-a1a6f1b7f6b8.png)

**Comment by GitOfZGT** [comment]
可以配置 {themeLinkTagId:""} 就不会默认添加link
