### ISSUE TITLE
打包后的主题css内有跟主题无关的样式，覆盖现有样式，导致样式错乱

### ISSUE THREAD

**Issue by yasuomang** [GitOfZGT/theme-css-extract-webpack-plugin#3]
打包后css：
![image](https://user-images.githubusercontent.com/62331159/143172153-aa94715c-5c4c-4d35-9395-58d1af6d81c3.png)
页面中是这样写的：
![image](https://user-images.githubusercontent.com/62331159/143172325-e52cd4c8-5bec-4d7d-855c-864308bd9528.png)

**Comment by yasuomang** [comment]
添加scoped可以解决问题，但这样我不确定隐藏的地方还会不会出现这种问题，导致某个角落出现样式问题

**Comment by GitOfZGT** [comment]
可以告诉我，安装在本地的@zougt/some-loader-utils的版本是哪个，我记得后面的版本不太可能出现这种情况了，奇怪了

**Comment by yasuomang** [comment]
我安装的是1.3.3版本

**Comment by yasuomang** [comment]
> 我安装的是1.3.3版本

我安装最新版本再试试

**Comment by yasuomang** [comment]
> > 我安装的是1.3.3版本
> 
> 我安装最新版本再试试

更新到最新版本还是会出现这个问题

**Comment by GitOfZGT** [comment]
将会在v1.4.0修复，并且1.4.0会支持在线动态主题（任意一个主颜色带的颜色梯度），不只是可以预设多个主题，
