### ISSUE TITLE
使用这个插件，还需要在webpack中配置some-loader-utils吗

### ISSUE THREAD

**Issue by sA-As** [GitOfZGT/theme-css-extract-webpack-plugin#4]

**Comment by GitOfZGT** [comment]
需要的,some-loader-utils是主体， theme-css-extract-webpack-plugin只是做加载器做不到的事：抽取独立的css，添加到html

**Comment by GitOfZGT** [comment]
已经在做新的特性，将会支持动态主题，比预设多个主题色更灵活的，到时some-loader-utils和 theme-css-extract-webpack-plugin必须同时配合实现，  vite的版本已经成型，webpack版还在实现中

**Comment by sA-As** [comment]
支持分割sass吗，我添加后会报Module build failed (from ./node_modules/css-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader 这个错误

**Comment by GitOfZGT** [comment]
> 支持分割sass吗，我添加后会报Module build failed (from ./node_modules/css-loader/dist/cjs.js): TypeError: this.getOptions is not a function at Object.loader 这个错误

是支持less和sass编译后等到主题css的， 这个报错应该不是这里插件导致，请移除我的插件后是否还会有同样的报错，确认是不是因为加入了插件导致， 因为插件内部没有使用this.getOptions

**Comment by sA-As** [comment]
升级sass-loader 版本后已解决
